---
title: "Data Analysis Final Milestone 4"
name: "Olivia Borgula"
date: 05/04/2024
format: html
editor: visual
---

**INTRODUCTION** This data analysis project will examine how incarceration, wealth and race intersect and play a role in voter registration in Baltimore City — an especially newsworthy topic ahead of elections season this November. Specifically, I will ask these five questions to guide my findings:

1. Which five Baltimore City community statistical areas had the lowest voter turnout percentage in the 2020 general election? Which five had the highest?

2. Is there a correlation between factors such as incarceration rate, median household income, internet access and walkability score and voter turnout in 2020? Have any of these factors improved since then? 

3. How has voter registration in Baltimore City changed from 2020 to 2024? 

**THE DATA**

```{r}

```


**Q1: Which five Baltimore City community statistical areas had the lowest voter turnout percentage in the 2020 general election? Which five had the highest?**
